-- Development/demo dataset for a clean PostgreSQL database.
-- PostgreSQL 18 provides uuidv7(), keeping seeded identifiers sortable and
-- consistent with identifiers generated by the Rust application.
INSERT INTO channels (id, name, kind, created_at, deleted_at)
VALUES
    (uuidv7(), 'main', 'public', extract(epoch FROM clock_timestamp())::bigint * 1000, NULL),
    (uuidv7(), 'general', 'public', extract(epoch FROM clock_timestamp())::bigint * 1000, NULL),
    (uuidv7(), 'random', 'public', extract(epoch FROM clock_timestamp())::bigint * 1000, NULL)
ON CONFLICT (name) DO UPDATE SET kind = 'public', deleted_at = NULL;

INSERT INTO messages (id, channel_id, username, text, created_at, edited, owner_session)
SELECT
    uuidv7(),
    c.id,
    format('test%s', (g.n % 6) + 1),
    format('Seeded message %s in #%s — history tier demo', g.n + 1, c.name),
    (extract(epoch FROM clock_timestamp())::bigint * 1000) - ((999 - g.n) * 60000),
    FALSE,
    '00000000-0000-0000-0000-000000000000'::uuid
FROM channels c
CROSS JOIN generate_series(0, 999) AS g(n)
WHERE c.name IN ('main', 'general', 'random')
  AND c.kind = 'public'
  AND c.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM messages existing
      WHERE existing.channel_id = c.id
  );
