{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vussa.fullname" . }}-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vussa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "vussa.fullname" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migration
          image: "{{ default .Values.image.repository .Values.migration.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MIGRATIONS_ONLY
              value: "true"
            - name: BIND_ADDRESS
              value: 127.0.0.1:3000
          envFrom:
            - secretRef:
                name: {{ default (include "vussa.fullname" .) .Values.externalSecret.name }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
{{- end }}
